name: ios
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [master]
    paths:
      - 'source/**'
      - 'express/**'
      - 'test/**'
      - 'project/ios/**'
      - '.github/workflows/ios.yml'

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  ios_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: wangzhaode/xcodebuild@1.2
        with:
          platform: iOS
          action: build
          configuration: release
          working-directory: project/ios
          scheme: MNN
          symroot: ./build
          verbosity: verbose

      - name: package-framework
        run: |
            ls project/ios/build
            echo '--------------------'
            zip -9 -y -r framework.zip project/ios/build

      - name: upload-framework
        uses: actions/upload-artifact@v3
        with:
          path: framework.zip
